name: orb_demo
description: Demonstrates how to use the orb plugin.

# Don't publish to pub.dev using `pub publish`.
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.4.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  orb:
    path: ../orb-sdk/orb

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
